import logo from './logo.svg';
import './App.css';
import RandomDecisionRender from './RandomDecisionRenderer';

function App() {

  const decisionArray = [
    'Open your heart',
    'What you expected will disapoint you',
    'Use your imagination',
    'Not what you think',
    'Out of control',
    'Sometime you need to be more ambitious',
    'Everything is going well',
    'Seek the true',
    'Just bet on it',
    'Your weakness will be revealed',
    'Good thinks come when you don\'t expect them',
    'It\'s up to you',
    'Set a new goal',
    'Of course',
    'Trust your intuition',
    'Within the next few weeks',
    'Keep calm and take your time to think',
    'You will be happy with what you did',
    'Perseverance will pay off',
    'Happiness is only temporary',
    'Curiousity killed the cat',
    'A new step is coming',
    'You will need to adapt',
    'That will be fine',
    'Let go and join the flow',
    'Wait',
    'Focus on what is important',
    'Be assertive',
    'Remove the first solution',
    'Something new is comming',
    'Don\'t ignore the obvious',
    'Keep an open mind',
    'Don\'t try to resist the change',
    'Mishaps are highly probable',
    'Adopt a positive attitude',
    'Unless you\'re alone',
    'Just enjoy it',
    'Easy come, easy go',
    'Reconsider your approach',
    'It will affect how others',
    'No!',
    'Unfavorable at this time',
    'Be fierce',
    'It\'s better not to expect',
    'Whatever you do results will be lasting',
    'Perfect timing',
    'Keep the ego, and it will do you more harm than good',
    'It\'s better to wait',
    'Stop judging',
    'Laugh about it',
    'Don\'t be too cautious',
    'That would be a waste of money',
    'You need to make the decision soon',
    'Don\'t let other people\'s oppinions affect you',
    'You will have to compromise',
    'Upgrade by any ways you can',
    'Be couragous',
    'See what happens',
    'Keep it to yourself',
    'It is the obvious thing to do',
    'Reconsider',
    'Don\'t blame yourself',
    'Get your priorities straight',
    'Yes!',
    'The stronger you commit, the more likely you are to succeed',
    'Emotional control',
    'Better late than never',
    'Just ignore it',
    'Don\'t worry',
    'Look for other options',
    'Startling events may occur',
    'A good time to start a new things',
    'A good time to start new things',
    'Out of the woods',
    'Believe in yourself',
    'Wait and see',
    'A bitter bill to swallow',
    'Listen to important people',
    'Be where your feet are',
    'Don\'t doubt it',
    'What must be, must be',
    'Act as if you already have it',
    'It doesn\'t matter',
    'Realistic thinking',
    'You are ready',
    'The sooner the better',
    'Move on',
    'Be consistent',
    'Talk of the devil and he sure to be appear',
    'Trust your judgement',
    'Tell them what it means to you',
    'Think carefully',
    'Absolutely not',
    'Be proactive',
    'Remove your own obstacles',
    'Don\'t wait',
    'Assert yourself',
    'Just say thank you',
    'You know what you want',
    'Settle it soon',
    'Carefully observe and you will have the answer',
    'It\'ll will bring good luck',
    'Make a list of "why not"',
    'Emotions will influence your decisions',
    'It\'s not the right time',
    'Something you didn\'t expect',
    'Sometime you have to make sacrifices',
    'If you believe',
    'There are other fish in the sea',
    'Don\'t hesitate',
    'Worthy trade-off',
    'A little is better than none',
    'Follow someone else\'s lead',
    'You are about to meet someone who can solve your problems',
    'It\'s not worth the struggle',
    'Maybe',
    'The answer may come to you in another language',
    'Say what you really think',
    'Don\'t give up',
    'Don\'t ask for anymore at this time',
    'Don\'t underestimate yourself',
    'A secret will be brought to light',
    'Pay the price',
    'Don\'t try to understand',
    'Miss the boat',
    'It is difficult but it\'s worth it',
    'You will be dissapointed',
    'It seems assured',
    'Take the chance',
    'Be patient',
    'There are clouds on the horizon',
    'Sincerity will lead to good results',
    'Call it a day',
    'Something is comming back',
    'To ensure the best decision, be calm',
    'There is a substantial to another situation',
    'You\'re right',
    'Extreme thinking is not helping you right now',
    'Don\'t worry too much',
    'Suspicious',
    'Don\'t delay any longer',
    'Every cloud has a silver lightning',
    'Remain flexible',
    'Hang in there',
    'Don\'t bet on it',
    'Just do it!',
    'Just a waste of time',
    'Set priorities',
    'Definitely not',
    'Don\'t be reluctant',
    'Think simple',
    'A blessing in disguise',
    'Ask your mother',
    'No problem',
    'Tell them how you feel',
    'The final decision is on you',
    'An important person is about to appear',
    'Don\'t forget to have fun',
    'Step out of your comfort zone',
    'Take action',
    'If you do as you said',
    'Try harder',
    'Listen carefully and you will have the answer',
    'Positive thinking',
    'It doesn\'t make any sense',
    'Appreciate what you have',
    'No matter what',
    'Your trust can be betrayed',
    'It will remain unpredictable',
    'If you can\'t stand it',
    'Giving up is a good choice',
    'It\'s sure to make things interesting',
    'Don\'t bite off more than you can chew',
    'You will know what you want to know',
    'Try again'
  ] 

  return (
    <div className="App">
      <div className='general-container'>
        <h1 className='title'> Decisive </h1>
        <RandomDecisionRender array={decisionArray} />
      </div>
    </div>
  );
}

export default App;
